### ISSUE TITLE
Sequence number error on configuration data

### ISSUE THREAD

**Issue by Jellybeanz1980** [DabblerDK/MEP-SW-ESP32#9] opened 2023-04-25 21:50 UTC
The issue about the "wrong sequence number" is not solved with the latest fix. The meter doesn't respond to the first request of the configuration. The MEP reader board re-sends the same request without increasing the sequence number as seen in the attachment.

![MEP Table2](https://user-images.githubusercontent.com/119456703/234411424-258655ec-f82d-4cc9-aa1b-4abab87e41b9.png)

Is the re-sending the same data packet in the line 386 of the NES-MEP-UI.ino causes the issue? The meter seem to respond when there is an error? Or the data packet at the first attempt is not complete somehow?

**Comment by glynge** [comment] 2023-04-26 15:42
Closing this issue as a duplicate of #7

**Closed as not planned by glynge** 2023-04-26 15:42 UTC
